### ISSUE TITLE
Problems with Custom Training

### ISSUE THREAD

**Issue by sourangshupal** [dronefreak/human-action-classification#1]
I prepared the training directory structure but facing problems of File not Found Error. It,s only picking only a single directory from the training folder and for rest of the classes directory I am getting error of File Not Found.

I have also updated the labels in retrained.txt

I am getting this error.

`WARNING:tensorflow:No files found
W0913 21:15:34.077941  9536 retrain.py:161] No files found
INFO:tensorflow:Looking for images in 'cricket_bowling'
I0913 21:15:34.081944  9536 retrain.py:156] Looking for images in 'cricket_bowling'
WARNING:tensorflow:No files found
W0913 21:15:34.095943  9536 retrain.py:161] No files found
INFO:tensorflow:Looking for images in 'croquet'
I0913 21:15:34.096971  9536 retrain.py:156] Looking for images in 'croquet'
WARNING:tensorflow:No files found
W0913 21:15:34.115942  9536 retrain.py:161] No files found
INFO:tensorflow:Looking for images in 'hands_closed'
I0913 21:15:34.116945  9536 retrain.py:156] Looking for images in 'hands_closed'
INFO:tensorflow:Looking for images in 'tennis_forehand'
I0913 21:15:34.144064  9536 retrain.py:156] Looking for images in 'tennis_forehand'
WARNING:tensorflow:No files found
W0913 21:15:34.163247  9536 retrain.py:161] No files found
INFO:tensorflow:Looking for images in 'tennis_serve'
I0913 21:15:34.165246  9536 retrain.py:156] Looking for images in 'tennis_serve'
WARNING:tensorflow:No files found
W0913 21:15:34.191455  9536 retrain.py:161] No files found
WARNING:tensorflow:From scripts\retrain.py:994: The name tf.logging.error is deprecated. Please use tf.compat.v1.logging.error instead.

W0913 21:15:34.193454  9536 deprecation_wrapper.py:119] From scripts\retrain.py:994: The name tf.logging.error is deprecated. Please use tf.compat.v1.logging.error instead.

ERROR:tensorflow:Only one valid folder of images found at training - multiple classes are needed for classification.
E0913 21:15:34.197569  9536 retrain.py:996] Only one valid folder of images found at training - multiple classes are needed for classification.`

![alt text](https://i.imgur.com/GO7Q4cY.png)

In this training directory structure whats that file001.txt  and what it consists of ?? Is it the labels.

Please help me out

**Comment by dronefreak** [comment]
Oh you need to rename you action folders to whatever your actions are.
Action-1 would be "tennis_serve" and so on.
Apologies for the late reply.

**Comment by sourangshupal** [comment]
In the training directory structure whats that file001.txt and what it consists of ??

**Comment by dronefreak** [comment]
Oh that is just a dummy file I had created for some tests. 
It has nothing to do with the training procedure. I shall remove that in my next commit.

**Comment by dronefreak** [comment]
Closing as this is resolved.
