### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by lisa676** [dronefreak/human-action-classification#10]
Hi @dronefreak  Thanks for this wonderful repository. I just run it in my PC it's working fine and evaluation time for single image is about 0.2-0.3s which is really fast but when I run webcam then output is quite slow I don't know what is the problem. My PC configuration is 

- Ubuntu 16

- CUDA 9

- Python 3.7 with TF 1.15.1 and OpenCV 4.1

I have suggestion that also add a piece of code for video from personal directory

**Comment by dronefreak** [comment]
Hi,

Apologies for the late reply. The code basically has to instantiate the GPU twice for every pose computation and scene classification, as I am yet to combine them into a single `tf.Session()`. In that case the instantiation would take place only once for both. 
The method suggested in this repo was part of an academic project, and I have not had the time to debug the instantiation issue. Please let me know if this helps with your query.
