### ISSUE TITLE
Could this project  be used for video?

### ISSUE THREAD

**Issue by tsutang-liao** [dronefreak/human-action-classification#18]
Could this project(run_image.py) be used for video ? (cuz this github project  has only two py script, run_image and run_webcam.py)
or how can I use this  to  project to apply for every single image in a folder( e.g.  there are 90 pics which are converted by a 3sec video and they are in a folder and named order by frame e.g. frame0,frame1,frame2..... )

**Comment by xander-m2k** [comment]
Yes.

**Comment by tsutang-liao** [comment]
> 

could you teach me how to achieve this goal? plz!!

**Comment by xander-m2k** [comment]
Just cycle through the files with a for loop or while loop, it's basic programming I'd say. Just Google some tutorials. You should only create an "issue" when you have found a bug or you have a problem with the software. This is not meant for "how do I make this". If you want to know how to do things, go get a degree or follow lots of tutorials.

Close this issue please, thanks.

**Comment by dronefreak** [comment]
Hello @tsutang-liao It is indeed not complicated to do what you need, you need a looping technique, its correct that you will find a lot of help on the other online platforms, like StackOverflow etc.
