### ISSUE TITLE
How to test the retrained model which was trained on custom dataset?

### ISSUE THREAD

**Issue by mm840511m** [dronefreak/human-action-classification#8]
Hi, I have followed the description in 'Training on  Custom Dataset' and the command 'python3 scripts/retrain.py --model_dir ... --image_dir=training/', so how do I test the retrained model?

**Comment by dronefreak** [comment]
Hi, 
Apologies for the late reply. You can test the effectiveness of the models using the `run_image.py` file. It will give you a prediction about the image at hand. Testing accuracy is revealed post training itself.
