### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by haduong825** [dronefreak/human-action-classification#9]
Hi @dronefreak,
Can you share me link or something about dataset of classification pose(upright and sitting). Can I retrain model with another pose(walking, running, ...).
Thank you so much!!!!!!

**Comment by dronefreak** [comment]
Hi,
I will have to look through my archives for the dataset. It is however easy to retrain the graphs on your custom dataset. Just follow the instructions in the repo for creating an identical directory sub-structure and you will be able to fine-tune the models on your own data.
